"use client";

/*
Model auto-generated by: https://github.com/pmndrs/gltfjsx
Author: SDC PERFORMANCE™️ (https://sketchfab.com/Lambo_SC04)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/free-la-tour-eiffel-8553f94d06e24cb4b0fde1080f281674
Title: ( FREE ) La tour Eiffel
*/

import { useEffect, useMemo, useRef } from "react";
import { useFrame, useLocalNodes } from "@react-three/fiber/webgpu";
import { useGLTF } from "@react-three/drei";
import * as TSL from "three/tsl";
import * as THREE from "three/webgpu";

/**
 * Ported from `threejs-conf-pmndrs/src/Tower.tsx`. Vite's `import.meta.env.BASE_URL`
 * becomes a plain public path; the asset lives at `public/hero-demo/`.
 */
const MODEL_URL = "/hero-demo/free__la_tour_eiffel.glb";

const TOWER_MESHES = ["Object_4", "Object_5", "Object_6"] as const;

export type TowerMode = "glow" | "metal" | "sparkle";

/**
 * The sparkle: the real tower's 20,000 bulbs going off for five minutes on
 * the hour, compressed into a permanent state.
 *
 * All in the fragment shader, driven by `TSL.time`: local space is diced
 * into cells, each cell gets a stable hash, and each hash phase-offsets a
 * shared slow cycle so a cell pops for a few tens of ms and stays dark for
 * the rest of it. The pops write to `emissiveNode`, which the pipeline's
 * emissive MRT attachment feeds straight into bloom — that's the glitter.
 * The base material is the dark iron the tower actually is at dusk.
 */
function makeSparkleNodes() {
  const cell = TSL.floor(TSL.positionLocal.mul(0.9));
  const seed = TSL.fract(
    TSL.sin(cell.dot(TSL.vec3(127.1, 311.7, 74.7))).mul(43758.5453),
  );
  // Every cell runs the same 2.5s cycle at a private phase; the step keeps
  // ~1.5% of it lit, so at any instant a sparse random scatter is popping.
  const cycle = TSL.fract(TSL.time.mul(0.4).add(seed));
  const flash = TSL.step(0.985, cycle);
  const brightness = seed.mul(0.6).add(0.4);

  return {
    emissiveNode: TSL.color("#fff3d0").mul(flash.mul(brightness).mul(8)),
  };
}

/**
 * The summit beacon: two opposed fake-volumetric beams, shaded the way
 * drei's `<SpotLight volumetric>` (pmndrs volumetric-spotlight example)
 * does its cone — a TSL port of that GLSL SpotLightMaterial, which can't
 * run on WebGPU directly. Two terms multiply:
 *
 * 1. Linear distance attenuation from the hub along the beam.
 * 2. `anglePower` falloff on the view-space normal: silhouette-edge
 *    fragments (normal ⟂ view) fade out, the tube's core (normal toward
 *    camera) stays bright. This is what turns a hard-edged cone into a
 *    soft light shaft with a luminous core.
 *
 * The example's third trick — depth-buffer soft intersection — is skipped:
 * these beams live in the sky and rarely cross geometry. Additive, no
 * depth write, double-sided (abs() covers the flipped back-face normals).
 */
function makeBeamNodes() {
  // Geometry below is translated so the hub is at y = 0, beam along +y.
  const along = TSL.positionLocal.y.div(BEAM_LENGTH).clamp(0.0, 1.0);
  const distanceFade = TSL.oneMinus(along);
  const angleFade = TSL.pow(TSL.abs(TSL.normalView.z), 4.0);
  return { opacityNode: distanceFade.mul(angleFade).mul(0.6) };
}

/** Beam length/flare in the tower's local (pre-scale-0.2) units. */
const BEAM_LENGTH = 600;
const BEAM_FLARE = 36;

function Beacon({ speed = 0.6 }: { speed?: number }) {
  const spinRef = useRef<THREE.Group>(null);

  const geometry = useMemo(() => {
    // High radial segmentation on purpose: the anglePower falloff shades by
    // interpolated silhouette normals, and a coarse tube shows facets.
    const g = new THREE.CylinderGeometry(
      BEAM_FLARE,
      1.5,
      BEAM_LENGTH,
      64,
      8,
      true,
    );
    // Hub end at the origin, beam extending along +y (then rotated flat).
    g.translate(0, BEAM_LENGTH / 2, 0);
    return g;
  }, []);

  // Module-level creator, so the memo inside `useLocalNodes` holds until the
  // shared TSL stores (or HMR) invalidate it. Both beams share the graph.
  const beam = useLocalNodes(makeBeamNodes);

  useFrame((_, delta) => {
    if (spinRef.current) spinRef.current.rotation.y += delta * speed;
  });

  return (
    <group ref={spinRef}>
      {[-Math.PI / 2, Math.PI / 2].map((roll) => (
        <mesh key={roll} geometry={geometry} rotation-z={roll}>
          <meshBasicNodeMaterial
            color="#ffeec2"
            transparent
            blending={THREE.AdditiveBlending}
            side={THREE.DoubleSide}
            depthWrite={false}
            opacityNode={beam.opacityNode}
          />
        </mesh>
      ))}
    </group>
  );
}

export function Tower({
  onReady,
  mode = "glow",
  beacon = false,
}: {
  onReady?: () => void;
  mode?: TowerMode;
  beacon?: boolean;
}) {
  const { nodes } = useGLTF(MODEL_URL) as unknown as {
    nodes: Record<string, THREE.Mesh>;
  };

  // `useGLTF` suspends, so reaching this effect means the geometry exists and
  // the meshes have committed — which is precisely when the camera can measure
  // a real bounding box. The camera used to poll for that with a
  // requestAnimationFrame retry loop, which fired inconsistently.
  useEffect(() => {
    onReady?.();
  }, [onReady, nodes]);

  // Registered through `useLocalNodes` (module-level creator, so the memo is
  // stable) rather than a bare `useMemo`: the graph re-creates when the shared
  // TSL stores invalidate — which is what makes editing the sparkle shader
  // hot-reload instead of requiring a refresh.
  const sparkle = useLocalNodes(makeSparkleNodes);

  // One declarative material per mode. Every mode spells out the full union
  // of props — R3F diffs JSX props on the *same* material instance, so a
  // value a mode omitted would linger from the previous mode instead of
  // resetting.
  const modeProps = {
    glow: {
      color: "#3a2a15",
      emissive: "#ff9f3f",
      emissiveIntensity: 1.6,
      metalness: 0.8,
      roughness: 0.45,
      emissiveNode: null,
    },
    metal: {
      color: "#878c92",
      emissive: "#000000",
      emissiveIntensity: 1,
      metalness: 0.85,
      roughness: 0.45,
      emissiveNode: null,
    },
    sparkle: {
      // Dark iron base; the glitter is entirely the emissive node feeding
      // the pipeline's emissive MRT attachment (→ bloom).
      color: "#15181c",
      emissive: "#000000",
      emissiveIntensity: 1,
      metalness: 0.85,
      roughness: 0.55,
      emissiveNode: sparkle.emissiveNode,
    },
  } as const satisfies Record<TowerMode, object>;

  // Local-space summit height, measured from the geometry rather than
  // hardcoded, so the beacon survives a model swap.
  const summitY = useMemo(() => {
    let maxY = 0;
    for (const name of TOWER_MESHES) {
      const g = nodes[name]?.geometry;
      if (!g) continue;
      if (!g.boundingBox) g.computeBoundingBox();
      maxY = Math.max(maxY, g.boundingBox?.max.y ?? 0);
    }
    return maxY;
  }, [nodes]);

  return (
    <group dispose={null} scale={0.2} rotation-y={THREE.MathUtils.degToRad(30)}>
      {/* The warm wash only exists to sell the glow mode; the metal and
          sparkle modes are lit by the sky like everything else. */}
      {mode === "glow" && (
        <pointLight
          position={[0, 10, 0]}
          color="#ffb35c"
          intensity={400}
          distance={100}
          decay={2}
        />
      )}

      {TOWER_MESHES.map((name) => (
        <mesh
          key={name}
          castShadow
          receiveShadow
          geometry={nodes[name].geometry}
        >
          <meshStandardNodeMaterial {...modeProps[mode]} />
        </mesh>
      ))}

      {beacon && (
        <group position={[0, summitY, 0]}>
          <Beacon />
        </group>
      )}
    </group>
  );
}

useGLTF.preload(MODEL_URL);
