"use client";

/*
Model auto-generated by: https://github.com/pmndrs/gltfjsx
Author: SDC PERFORMANCE™️ (https://sketchfab.com/Lambo_SC04)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/free-la-tour-eiffel-8553f94d06e24cb4b0fde1080f281674
Title: ( FREE ) La tour Eiffel
*/

import { useCallback, useEffect, useMemo, useRef } from "react";
import {
  createPortal,
  useFrame,
  useLocalNodes,
  useUniforms,
} from "@react-three/fiber/webgpu";
import { useGLTF } from "@react-three/drei";
import * as TSL from "three/tsl";
import * as THREE from "three/webgpu";

/**
 * Ported from `threejs-conf-pmndrs/src/Tower.tsx`. Vite's `import.meta.env.BASE_URL`
 * becomes a plain public path; the asset lives at `public/hero-demo/`.
 */
const MODEL_URL = "/hero-demo/free__la_tour_eiffel.glb";

const TOWER_MESHES = ["Object_4", "Object_5", "Object_6"] as const;

/** Transform shared by the visible tower and its depth twin. */
const TOWER_MODEL_SCALE = 0.2;
const TOWER_MODEL_YAW = THREE.MathUtils.degToRad(30);

/** Model height below which tower geometry cannot overlap the lettering. */
const OCCLUDER_MIN_Y = 30;

/** Caches trimmed geometry for each source mesh. */
const occluderCache = new WeakMap<THREE.BufferGeometry, THREE.BufferGeometry>();

/** Builds depth geometry from triangles that can overlap the lettering. */
function occluderGeometry(source: THREE.BufferGeometry) {
  const cached = occluderCache.get(source);
  if (cached) return cached;

  const position = source.getAttribute("position");
  const index = source.getIndex();
  const triangles = (index?.count ?? position.count) / 3;
  const kept: number[] = [];

  for (let t = 0; t < triangles; t += 1) {
    const o = t * 3;
    const a = index ? index.getX(o) : o;
    const b = index ? index.getX(o + 1) : o + 1;
    const c = index ? index.getX(o + 2) : o + 2;
    const top = Math.max(position.getY(a), position.getY(b), position.getY(c));
    if (top >= OCCLUDER_MIN_Y) kept.push(a, b, c);
  }

  const twin = new THREE.BufferGeometry();
  twin.setAttribute("position", position);
  twin.setIndex(kept);
  // Source bounds remain conservative because the position buffer is shared.
  if (!source.boundingBox) source.computeBoundingBox();
  if (!source.boundingSphere) source.computeBoundingSphere();
  twin.boundingBox = source.boundingBox?.clone() ?? null;
  twin.boundingSphere = source.boundingSphere?.clone() ?? null;
  occluderCache.set(source, twin);
  return twin;
}

/** Depth-only material for lettering occlusion. */
const occluderMaterial = new THREE.MeshBasicNodeMaterial({ colorWrite: false });

/** Renders antenna parts and duplicates each arm into a crossed pair. */
function antennaMeshes(
  parts: { kind: AntennaPart["kind"]; geometry: THREE.BufferGeometry }[],
  material: React.ReactNode,
) {
  return parts.map(({ kind, geometry }, i) => (
    <group key={i}>
      <mesh geometry={geometry}>{material}</mesh>
      {kind === "arms" && (
        <mesh geometry={geometry} rotation-y={Math.PI / 2}>
          {material}
        </mesh>
      )}
    </group>
  ));
}

/** Renders the tower silhouette into the lettering scene as depth only. */
function DepthTwin({
  nodes,
  summitY,
  antennaGeometries,
  worldScale,
  scene,
}: {
  nodes: Record<string, THREE.Mesh>;
  summitY: number;
  antennaGeometries: {
    kind: AntennaPart["kind"];
    geometry: THREE.BufferGeometry;
  }[];
  worldScale: number;
  scene: THREE.Scene;
}) {
  const geometries = useMemo(
    () => TOWER_MESHES.map((name) => occluderGeometry(nodes[name].geometry)),
    [nodes],
  );

  return createPortal(
    // Shared GLB buffers outlive this portal and must not be disposed here.
    <group dispose={null} scale={worldScale}>
      <group scale={TOWER_MODEL_SCALE} rotation-y={TOWER_MODEL_YAW}>
        {geometries.map((geometry, i) => (
          <mesh
            key={TOWER_MESHES[i]}
            geometry={geometry}
            material={occluderMaterial}
          />
        ))}
        <group position={[0, summitY, 0]}>
          {antennaMeshes(
            antennaGeometries,
            <primitive object={occluderMaterial} attach="material" />,
          )}
        </group>
      </group>
    </group>,
    scene,
  );
}

export type TowerMode = "glow" | "metal" | "sparkle";

/**
 * The sparkle: the real tower's 20,000 bulbs going off for five minutes on
 * the hour, compressed into a permanent state.
 *
 * All in the fragment shader, driven by `TSL.time`: local space is diced
 * into cells, each cell gets a stable hash, and each hash phase-offsets a
 * shared slow cycle so a cell pops for a few tens of ms and stays dark for
 * the rest of it. The pops write to `emissiveNode`, which the pipeline's
 * emissive MRT attachment feeds straight into bloom — that's the glitter.
 * The base material is the dark iron the tower actually is at dusk.
 */
function makeSparkleNodes(
  lightLevel: THREE.UniformNode<"float", number>,
) {
  const cell = TSL.floor(TSL.positionLocal.mul(0.9));
  const seed = TSL.fract(
    TSL.sin(cell.dot(TSL.vec3(127.1, 311.7, 74.7))).mul(43758.5453),
  );
  // Every cell runs the same 2.5s cycle at a private phase; the step keeps
  // ~1.5% of it lit, so at any instant a sparse random scatter is popping.
  const cycle = TSL.fract(TSL.time.mul(0.4).add(seed));
  const flash = TSL.step(0.985, cycle);
  const brightness = seed.mul(0.6).add(0.4);

  return {
    emissiveNode: TSL.color("#fff3d0").mul(
      flash.mul(brightness).mul(8).mul(lightLevel),
    ),
  };
}

/**
 * The summit beacon: two opposed fake-volumetric beams, shaded the way
 * drei's `<SpotLight volumetric>` (pmndrs volumetric-spotlight example)
 * does its cone — a TSL port of that GLSL SpotLightMaterial, which can't
 * run on WebGPU directly. Two terms multiply:
 *
 * 1. Linear distance attenuation from the hub along the beam.
 * 2. `anglePower` falloff on the view-space normal: silhouette-edge
 *    fragments (normal ⟂ view) fade out, the tube's core (normal toward
 *    camera) stays bright. This is what turns a hard-edged cone into a
 *    soft light shaft with a luminous core.
 *
 * The example's third trick — depth-buffer soft intersection — is skipped:
 * these beams live in the sky and rarely cross geometry. Additive, no
 * depth write, double-sided (abs() covers the flipped back-face normals).
 */
function makeBeamNodes(lightLevel: THREE.UniformNode<"float", number>) {
  // Geometry below is translated so the hub is at y = 0, beam along +y.
  const along = TSL.positionLocal.y.div(BEAM_LENGTH).clamp(0.0, 1.0);
  const distanceFade = TSL.oneMinus(along);
  const angleFade = TSL.pow(TSL.abs(TSL.normalView.z), 4.0);
  return {
    opacityNode: distanceFade.mul(angleFade).mul(0.6).mul(lightLevel),
  };
}

/** Beam length/flare in the tower's local (pre-scale-0.2) units. */
const BEAM_LENGTH = 600;
const BEAM_FLARE = 36;

/** Antenna dimensions in unscaled tower model units. */
const ANTENNA_REACH = 9;
const ANTENNA_ROOT = 2;
type AntennaPart = {
  kind: "mast" | "collar" | "arms";
  y: number;
  size: [number, number, number];
};

const ANTENNA_PARTS: AntennaPart[] = [
  { kind: "mast", y: 0, size: [0.18, 0.5, ANTENNA_REACH + ANTENNA_ROOT] },
  { kind: "collar", y: 1.5, size: [0.9, 1.1, 0.9] },
  { kind: "arms", y: 4, size: [0.09, 0.09, 3] },
  { kind: "arms", y: 6.2, size: [0.07, 0.07, 2] },
];

/** Builds an antenna member anchored at the tower summit. */
function makeAntennaGeometry({ kind, y, size: [rt, rb, h] }: AntennaPart) {
  const g = new THREE.CylinderGeometry(rt, rb, h, kind === "arms" ? 8 : 12);
  if (kind === "mast") {
    g.translate(0, h / 2 - ANTENNA_ROOT, 0);
  } else if (kind === "collar") {
    g.translate(0, y, 0);
  } else {
    // Lay each arm flat before rendering it in a crossed pair.
    g.rotateZ(Math.PI / 2);
    g.translate(0, y, 0);
  }
  return g;
}

function Beacon({
  lightLevel,
  speed = 0.6,
}: {
  lightLevel: THREE.UniformNode<"float", number>;
  speed?: number;
}) {
  const spinRef = useRef<THREE.Group>(null);

  const geometry = useMemo(() => {
    // High radial segmentation on purpose: the anglePower falloff shades by
    // interpolated silhouette normals, and a coarse tube shows facets.
    const g = new THREE.CylinderGeometry(
      BEAM_FLARE,
      1.5,
      BEAM_LENGTH,
      64,
      8,
      true,
    );
    // Hub end at the origin, beam extending along +y (then rotated flat).
    g.translate(0, BEAM_LENGTH / 2, 0);
    return g;
  }, []);

  const createBeamNodes = useCallback(
    () => makeBeamNodes(lightLevel),
    [lightLevel],
  );
  // Both beams share one graph and light uniform.
  const beam = useLocalNodes(createBeamNodes);

  useFrame((_, delta) => {
    if (spinRef.current) spinRef.current.rotation.y += delta * speed;
  });

  return (
    <group ref={spinRef}>
      {[-Math.PI / 2, Math.PI / 2].map((roll) => (
        <mesh key={roll} geometry={geometry} rotation-z={roll}>
          <meshBasicNodeMaterial
            color="#ffeec2"
            transparent
            blending={THREE.AdditiveBlending}
            side={THREE.DoubleSide}
            depthWrite={false}
            opacityNode={beam.opacityNode}
          />
        </mesh>
      ))}
    </group>
  );
}

export function Tower({
  onReady,
  mode = "glow",
  beacon = false,
  lightLevel = 1,
  occluderScene,
  worldScale = 1,
}: {
  onReady?: () => void;
  mode?: TowerMode;
  beacon?: boolean;
  /** Light level from 0 in daylight to 1 at night. */
  lightLevel?: number;
  /** Scene that receives the depth-only tower twin. */
  occluderScene?: THREE.Scene;
  /** Scale shared with the main scene. */
  worldScale?: number;
}) {
  const { nodes } = useGLTF(MODEL_URL) as unknown as {
    nodes: Record<string, THREE.Mesh>;
  };

  // `useGLTF` suspends, so reaching this effect means the geometry exists and
  // the meshes have committed — which is precisely when the camera can measure
  // a real bounding box. The camera used to poll for that with a
  // requestAnimationFrame retry loop, which fired inconsistently.
  useEffect(() => {
    onReady?.();
  }, [onReady, nodes]);

  const lightKnobs = useUniforms(
    { lightLevel },
    "heroTowerLights",
  ) as unknown as Record<
    "lightLevel",
    THREE.UniformNode<"float", number>
  >;
  const createSparkleNodes = useCallback(
    () => makeSparkleNodes(lightKnobs.lightLevel),
    [lightKnobs.lightLevel],
  );
  // Update the light uniform without rebuilding the shader graph.
  const sparkle = useLocalNodes(createSparkleNodes);

  // Blend bronze daylight paint into a darker illuminated night base.
  const glowBaseColor = useMemo(
    () =>
      new THREE.Color("#a96843").lerp(
        new THREE.Color("#3a2a15"),
        lightLevel,
      ),
    [lightLevel],
  );
  const sparkleBaseColor = useMemo(
    () =>
      new THREE.Color("#80553d").lerp(
        new THREE.Color("#15181c"),
        lightLevel,
      ),
    [lightLevel],
  );

  // One declarative material per mode. Every mode spells out the full union
  // of props — R3F diffs JSX props on the *same* material instance, so a
  // value a mode omitted would linger from the previous mode instead of
  // resetting.
  const modeProps = {
    glow: {
      color: glowBaseColor,
      emissive: "#ff9f3f",
      emissiveIntensity: 1.6 * lightLevel,
      metalness: THREE.MathUtils.lerp(0.18, 0.8, lightLevel),
      roughness: THREE.MathUtils.lerp(0.55, 0.45, lightLevel),
      envMapIntensity: THREE.MathUtils.lerp(1.5, 1, lightLevel),
      emissiveNode: null,
    },
    metal: {
      color: "#878c92",
      emissive: "#000000",
      emissiveIntensity: 1,
      metalness: 0.85,
      roughness: 0.45,
      envMapIntensity: 1,
      emissiveNode: null,
    },
    sparkle: {
      // Dark iron base; the glitter is entirely the emissive node feeding
      // the pipeline's emissive MRT attachment (→ bloom).
      color: sparkleBaseColor,
      emissive: "#000000",
      emissiveIntensity: 1,
      metalness: 0.85,
      roughness: 0.55,
      envMapIntensity: THREE.MathUtils.lerp(1.3, 1, lightLevel),
      emissiveNode: sparkle.emissiveNode,
    },
  } as const satisfies Record<TowerMode, object>;

  // Derive the summit height from the loaded tower geometry.
  const summitY = useMemo(() => {
    let maxY = 0;
    for (const name of TOWER_MESHES) {
      const g = nodes[name]?.geometry;
      if (!g) continue;
      if (!g.boundingBox) g.computeBoundingBox();
      maxY = Math.max(maxY, g.boundingBox?.max.y ?? 0);
    }
    return maxY;
  }, [nodes]);

  // Reuse antenna geometry across visible and depth-only renders.
  const antennaGeometries = useMemo(
    () =>
      ANTENNA_PARTS.map((part) => ({
        kind: part.kind,
        geometry: makeAntennaGeometry(part),
      })),
    [],
  );

  return (
    <>
      <group
        dispose={null}
        scale={TOWER_MODEL_SCALE}
        rotation-y={TOWER_MODEL_YAW}
      >
        {/* Keep the light mounted so mode changes do not rebuild shaders.
            Group scale × world scale is 1, so these are world units: the
            floodlight sits up in the arches and reaches past the feet to
            the ring path, rather than a hotspot under the centre that has
            died out by the time it meets the legs. */}
        <pointLight
          position={[0, 55, 0]}
          color="#ffb35c"
          intensity={mode === "glow" ? 7000 * lightLevel : 0}
          distance={300}
          decay={2}
        />

        {TOWER_MESHES.map((name) => (
          <mesh
            key={name}
            castShadow
            receiveShadow
            geometry={nodes[name].geometry}
          >
            <meshStandardNodeMaterial {...modeProps[mode]} />
          </mesh>
        ))}

        {/* Match the antenna material to the active tower mode. */}
        <group position={[0, summitY, 0]}>
          {antennaMeshes(
            antennaGeometries,
            <meshStandardNodeMaterial {...modeProps[mode]} />,
          )}
        </group>

        {beacon && (
          <group position={[0, summitY + ANTENNA_REACH, 0]}>
            <Beacon lightLevel={lightKnobs.lightLevel} />
          </group>
        )}
      </group>

      {occluderScene && (
        <DepthTwin
          nodes={nodes}
          summitY={summitY}
          antennaGeometries={antennaGeometries}
          worldScale={worldScale}
          scene={occluderScene}
        />
      )}
    </>
  );
}

useGLTF.preload(MODEL_URL);
